### ISSUE TITLE
Update `forge-std` to 1.0.0

### ISSUE THREAD

**Issue by TomAFrench** [balancer/balancer-v2-monorepo#1999]
We should update our version of `forge-std` to 1.0.0. I've updated locally and ran into the error described here: https://github.com/foundry-rs/forge-std/issues/215.

Once this is fixed then we can update.

Update as of 5/2/23: We have updated forge in #2448... but some (different) issues remain. We are getting intermittent failures now on the same two pesky join/exit tests.

**Comment by nventuro** [comment]
Keep in mind some of our tests will also fail in 1.0.0 and need fixing: see [this comment](https://github.com/foundry-rs/forge-std/pull/184#issuecomment-1279780464) and [this other one](https://github.com/foundry-rs/forge-std/pull/184#issuecomment-1285531807) for a more detailed explanation.

**Comment by jubeira** [comment]
See #2448
