### ISSUE TITLE
GaugeAdder V4

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v2-monorepo#2257]
The current gauge adder has some functionality that we are not using, and it can be improved a bit to make it more user friendly.

Concretely:
- Instead of having one `add***Factory` function for each type, we can do an `addType` taking a human-readable string, and then `addFactory` with an existing string type.
- The check for Ethereum gauges (BAL80-WETH20 pool) is unnecessary.

The gauge adder is, at the end of the day, a gauge factory allowlist that prevents bad gauges from being added to the controller (i.e. not from valid factories). The gauge type in the adder will be separate from the type in the controller, which is currently not being used (it's only used to assign a weight for each gauge type, which is always 1 and is expected to continue that way).

**Comment by nventuro** [comment]
Suggested interface and sample usage:

```
.createGaugeType("Polygon")
.addGaugeFactory(0x1234, "Polygon")
.addGauge(0x1234, "Polygon")
```

I wouldn't use the underlying GaugeController gauge types: we can simply create a new type (e.g. 'General', or even 'GaugeAdderV4') and add all gauges there.

**Comment by jubeira** [comment]
See #2494 and https://github.com/balancer/balancer-deployments/pull/28.
