### ISSUE TITLE
Reentrancy protection disables Balancer swaps after a flashloan

### ISSUE THREAD

**Issue by sandybradley** [balancer/balancer-v2-monorepo#2346]
# Problem
Currently it is not possible to swap on Balancer after a Balancer flashloan because of reentrancy protection. For arbitrage routes entirely within Balancer, I understand batchswap can be used as an internal flashloan but this is not my use case. Frankly this is lame.

# Solution
Re-work reentrancy protection to allow for swaps in a flashloan.

**Comment by sandybradley** [comment]
Thanks for a quick response. Vault security should take precedence. 

My use case is depositing and withdrawing various staked eth derivatives along with Balancer swaps. I can use Aave and BentoBox for flashloans.

**Comment by nventuro** [comment]
Thank you. We'll consider such cases in the future, when the time comes to work on a new version.

Since we cannot do anything to help with this at the moment, I'm closing this issue.
