### ISSUE TITLE
Equation description/functionality not consistent with documentation?

### ISSUE THREAD

**Issue by enzoevers** [balancer/balancer-v2-monorepo#2390]
In the documentation in StableMath.sol for the `_calcOutGivenIn()` and `_calcInGivenOut()` it indicates that the $\frac{D}{An^n}$ is subtracted, while in the documentation on the [website](https://docs.balancer.fi/reference/math/stable-math.html#trade-equations) it indicates that it is added. Deriving it myself from the invariant shows that the documentation in the code should be updated.

https://github.com/balancer/balancer-v2-monorepo/blob/4a3275a9a82ab321740b21025696f33402f1d654/pkg/pool-stable/contracts/StableMath.sol#L138

**Comment by enzoevers** [comment]
Also, is there actually a reason why the `y` is calculated iteratively other than being able to re-use `_getTokenBalanceGivenInvariantAndAllOtherBalances()`? Because as it seems to me, this is a polynomial for which all the values but `y` are known. Meaning that we can simply find the root using the standard formula $finalBalance = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$. This can be used with only the `+` case as can be seen after looking at the constraints that the terms imply. Resulting in:

$finalBalance = \frac{-b + \sqrt{b^2 - 4ac}}{2a}$.

With:
$a = 1$
$b = \left( \frac{D}{An^n} + \sum_{j \neq out} x_{j}^{'} - D \right)$
$c = -\frac{D^{n+1}}{An^{2n} \prod_{j \neq out} x_{j}^{'}}$

Doing some test calculations with this seems like it gives the same output other than some rounding errors. This would then also mean that the whole loop in `_getTokenBalanceGivenInvariantAndAllOtherBalances()` can be optimized out. At least if I didn't miss any details which would mean that my assumptions are oversimplified.

**Comment by nventuro** [comment]
Hi @enzoevers! Thanks for looking into this.

>Deriving it myself from the invariant shows that the documentation in the code should be updated.

It's not impossible for the code comment to be wrong - I haven't looked at this code in a while, so it'll take some time for me to dig up the original references and compare.

>Also, is there actually a reason why the y is calculated iteratively other than being able to re-use _getTokenBalanceGivenInvariantAndAllOtherBalances()?

Note that reusing this function is not a small benefit. We get large code size savings since we don't have to implement `sqrt`, and we can more easily reason about rounding errors. Keep in mind this was developed almost two years ago however: there's now a couple well-tested implementations of `sqrt` that mighjt be suitable, but I'd not change this code without very strong motivation.

**Comment by enzoevers** [comment]
Hi @nventuro. Thank you for your response.

I'm not necessarily suggesting to immediately change the implementation of StableMath. The main reason why I asked this question is that reasoning about the behavior of the stable math becomes a lot easier with a 'simple' input-output function rather than with an iterative algorithm.

So if it is indeed true that the polynomial as described on the website should be the StableMath OutGivenIn function, then that would be great. But as stated before, it seems that the amplification factor is less sensitive for the polynomial function.

Of course, when it comes to code size I get that optimizations have to be made. I have seen the effort that has gone into the Balancer code regarding size optimizations.

So I hope to hear about the possible details and differences between the stated polynomial and the iterative algorithm.

**Comment by enzoevers** [comment]
I would like to keep this issue open, or at least keep the discussion going, about the difference between the behavior of the polynomial and the iterative algorithm.
