### ISSUE TITLE
BPT_IN_FOR_EXACT_TOKENS_OUT accuracy issue

### ISSUE THREAD

**Issue by sparrowDom** [balancer/balancer-v2-monorepo#2541]
**Problem:**
When exiting the pool using BPT_IN_FOR_EXACT_TOKENS_OUT I've encountered accuracy issues that seem like a rounding error. 

**Reproduction**
See these 2 tenderly transactions where [1st one succeeds](https://dashboard.tenderly.co/sparrowOrigin/sparrow-s-project/fork/fea6b91f-a659-4674-9d3a-fc0561cef55c/simulation/e8d0cb7c-6e10-4750-b76b-1364130daf35/debugger?trace=0.2) and [2nd one fails](https://dashboard.tenderly.co/sparrowOrigin/sparrow-s-project/fork/fea6b91f-a659-4674-9d3a-fc0561cef55c/simulation/900bc9f7-3c49-4b08-9d89-c534234bf5b1/debugger?trace=0.13). 

Both are exiting rETH/WETH pool in BPT_IN_FOR_EXACT_TOKENS_OUT mode with the same `minAmountsOut` in the exitPoolRequest as well `amountsOut` encoded in the user encoded data of the `BPT_IN_FOR_EXACT_TOKENS_OUT` mode. (format:  [BPT_IN_FOR_EXACT_TOKENS_OUT, amountsOut, maxBPTAmountIn] )

First one succeeds because it is withdrawing 1.0 rETH and the second one fails because it is withdrawing 0.8123 rETH. Both have been given sufficient BPT in the encoded request so that is not the issue. [This require](https://github.com/balancer/balancer-v2-monorepo/blob/75cd38ed657c84ac7a81c733d1636b161e191b0f/pkg/vault/contracts/PoolBalances.sol#L268) in the code is the one that triggers the exception. Using Tenderly Evaluate to see the value of variables in the execution: 
<img width="783" alt="Screenshot 2023-08-04 at 22 00 38" src="https://github.com/balancer/balancer-v2-monorepo/assets/579910/bdaebdca-a951-4ca7-a5c3-342f266b1575">
<img width="782" alt="Screenshot 2023-08-04 at 22 01 15" src="https://github.com/balancer/balancer-v2-monorepo/assets/579910/e4014cd1-0cfe-419a-8457-e18d702d301b">

from the above debugger it is evident that the actual change is off by 1 WEI from the limit number that has been passed in the request. And because it is smaller than the `minAmountsOut` the transaction fails.

**Comment by jubeira** [comment]
Hi @sparrowDom, thanks for looking into this.

Rounding in pool's favor is on purpose; at some point the math inside the pools is not perfectly accurate (e.g. when upscaling and downscaling), and that means that the calculated amounts might be off with respect to a scenario with no precision loss.

To prevent the txs from failing, I'd suggest being more permissive with the minimum amounts in or out in general. Some wei won't make any economic difference in practice, but will help the txs go through when the rounding happens. You can query the swaps before executing them too.
