### ISSUE TITLE
Was `pool-utils/contracts/oracle/QueryProcessor.sol` ever audited? 

### ISSUE THREAD

**Issue by xenide** [balancer/balancer-v2-monorepo#2570]
We're thinking of using the oracle code from [here](https://github.com/balancer/balancer-v2-monorepo/blob/903d34e491a5e9c5d59dabf512c7addf1ccf9bbd/pkg/pool-utils/contracts/oracle/QueryProcessor.sol) , but it seems like all oracle code infra was deleted in [this commit](https://github.com/balancer/balancer-v2-monorepo/commit/4b4a9bc623b802908d324e5915f6da823bb45d23). 

I looked through all audit reports and none of them mention those oracle code. Can I confirm that: 

1. `QueryProcessor.sol` and associated files (such as `Samples.sol` and `Buffer.sol`) have never been audited? 
   - if they've been, where are the audit reports? 
2. Therefore none of the pools deployed in production now have those oracle code? 
   - I found a `MetaStablePool` on [mainnet](https://etherscan.io/address/0x32296969ef14eb0c6d29669c550d4a0449130230#code) that had the oracle code deployed and [another one](https://etherscan.io/address/0x9f383f91c89cbd649c700c2bf69c2a828af299aa#code)

**Comment by xenide** [comment]
paging @nventuro, could I trouble you take a quick look at this?

**Comment by nventuro** [comment]
Hm I don't recall exactly, but I don't think it was. None of the [audits](https://github.com/balancer/balancer-v2-monorepo/tree/master/audits) mention it, and I think it was developed and then removed in the time between deployment of v2 (April 2021) and deployment of the first set of stable pools (around Aug/Sept 2021).

From what I remember, we dropped it because we were unsure the oracles provided sufficient value to warrant the gas cost increases during normal operations, not due to correctness or security concerns.

**Comment by xenide** [comment]
hey @nventuro thanks for responding. In that case, then we're looking at cases of having deployed code without having gone through an audit (as seen in those two pools above). 

Do you think this is what happened?

**Comment by nventuro** [comment]
Looking at [the deployments](https://github.com/balancer/balancer-deployments?tab=readme-ov-file#deprecated-deployments), it seems like the only instance of a pool with a price oracle was the one you identified: https://github.com/balancer/balancer-deployments/tree/master/tasks/deprecated/20210727-meta-stable-pool

**Comment by EndymionJkb** [comment]
> Looking at [the deployments](https://github.com/balancer/balancer-deployments?tab=readme-ov-file#deprecated-deployments), it seems like the only instance of a pool factory with a price oracle was the one you identified: https://github.com/balancer/balancer-deployments/tree/master/tasks/deprecated/20210727-meta-stable-pool

Well, we also had the oracle weighted pool: https://github.com/balancer/balancer-deployments/tree/master/tasks/deprecated/20210418-weighted-pool (WeightedPool2Tokens).

My recollection is we were refactoring the pool code mid '22 (e.g., BPT protocol fees, composable pools), and deciding whether we wanted to retain the oracle functionality, which would likely have required maintaining multiple pool versions going forward. We wanted a single stable pool, and dropped the oracle functionality to keep it simple. The oracles just weren't used enough to be worth maintaining. And there was significant gas overhead if the oracle was turned on, as updating the oracle added storage writes to every operation.

I don't think the code was *formally* audited, but I seem to remember Certora at least looking at it. We certainly reviewed it extensively internally, and they were used in production without any issues (e.g., all the core, seeded weighted pools had oracles).
